# 腾讯云 CNB 云构建配置
main:
  push:
    - services:
        - docker
      imports:
        - https://cnb.cool/longlian.online/env/-/blob/main/loc.yml
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest"
          exports:
            info: IMAGE_TAG

        - name: docker build
          script: docker build -t $IMAGE_TAG .

        - name: push image
          script: docker push $IMAGE_TAG

        - name: deploy to server
          image: tencentcom/ssh
          settings:
            host:
              - ${REMOTE_HOST}
            username: ${REMOTE_USERNAME}
            password: ${REMOTE_PASSWORD}
            port: ${REMOTE_PORT}
            command_timeout: 2m
            script: |
              sudo su
              echo ${IMAGE_TAG}
              docker login -u "${CNB_DOCKER_USERNAME}" -p "${CNB_DOCKER_PASSWORD}" "${CNB_DOCKER_URL}"
              sudo docker pull ${IMAGE_TAG}
              sudo docker stop ${APP_NAME} || true
              sudo docker rm ${APP_NAME} || true
              sudo docker run --network 1panel-network --env-file /home/loc/.env.sit.deploy -d --name ${APP_NAME} -p 25923:3000 $IMAGE_TAG

$:
  tag_deploy.production:
    - name: production
      imports:
        - https://cnb.cool/longlian.online/env/-/blob/main/loc-prod.yml
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest"
          exports:
            info: IMAGE_TAG
        - name: deploy to server
          image: tencentcom/ssh
          settings:
            host:
              - ${REMOTE_HOST}
            username: ${REMOTE_USERNAME}
            key: ${REMOTE_SSH_KEY}
            port: ${REMOTE_PORT}
            command_timeout: 2m
            script: |
              sudo su
              echo ${IMAGE_TAG}
              docker login -u "${CNB_DOCKER_USERNAME}" -p "${CNB_DOCKER_PASSWORD}" "${CNB_DOCKER_URL}"
              sudo docker pull ${IMAGE_TAG}
              sudo docker stop ${APP_NAME} || true
              sudo docker rm ${APP_NAME} || true
              sudo docker run --network 1panel-network --env-file ~/loc/.env -d --name ${APP_NAME} -p 25923:3000 $IMAGE_TAG

prod:
  push:
    - services:
        - docker
      imports:
        - https://cnb.cool/longlian.online/env/-/blob/main/loc-prod.yml
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest"
          exports:
            info: IMAGE_TAG

        - name: docker build
          script: docker build -t $IMAGE_TAG .

        - name: push image
          script: docker push $IMAGE_TAG
